### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by mike-aungsan** [Nimrodda/gcm_server#1]
Any instruction on how to run this server from Linux Console?

**Comment by Nimrodda** [comment]
I wrote this server for developing and testing proposes with IntelliJ IDEA only. To run from command line you will have to build a "fat jar" that contains also the dependencies of the server in the same built jar file. Then you run it with `java -jar jarfile`. Note that Gradle now has an "application" plugin which helps with that so you might want to check that out as well.

**Comment by Nimrodda** [comment]
OK I updated gradle.build for you ;) From command line:`./gradlew run`
